import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ProductProvider } from "./context/Product/ProductContext";
import NavBarComponent from "./components/navBar/NavBarComponent";
import styles from "./layout.module.scss";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ProductProvider>
      <html lang="en">
        <body className={styles.container}>
          <NavBarComponent />
          {children}
        </body>
      </html>
    </ProductProvider>
  );
}
